FROM python:latest
WORKDIR /opt/app-root/bin
RUN pip install --upgrade jupyterlab 
WORKDIR /opt/app-root/src
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]

