FROM python:latest

WORKDIR /opt/app-root/bin

RUN pip install --upgrade pip jupyterlab

WORKDIR /opt/app-root/src

COPY requirements.txt .
COPY assignment8-hassandawy.ipynb .
COPY assignment8-liamdurcan.ipynb .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8888

CMD ["jupyter", "lab", "--port=8888", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]